// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRrfFFyPTp1s-Zk-SLK0Y0iVjdJUhPl8g',
    appId: '1:711200537692:web:57e6f70ff3d17d4cebfa99',
    messagingSenderId: '711200537692',
    projectId: 'spotify-192dif9ab12',
    authDomain: 'spotify-192dif9ab12.firebaseapp.com',
    storageBucket: 'spotify-192dif9ab12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYtvAG1ruW8ZhMlr5VDwhtlGqChuNx3S0',
    appId: '1:711200537692:android:a277ebe424773925ebfa99',
    messagingSenderId: '711200537692',
    projectId: 'spotify-192dif9ab12',
    storageBucket: 'spotify-192dif9ab12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDtdnPLoOEoZY2voAm9_BOvgHZvU6DOhk',
    appId: '1:711200537692:ios:256356f23e066db2ebfa99',
    messagingSenderId: '711200537692',
    projectId: 'spotify-192dif9ab12',
    storageBucket: 'spotify-192dif9ab12.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDtdnPLoOEoZY2voAm9_BOvgHZvU6DOhk',
    appId: '1:711200537692:ios:256356f23e066db2ebfa99',
    messagingSenderId: '711200537692',
    projectId: 'spotify-192dif9ab12',
    storageBucket: 'spotify-192dif9ab12.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRrfFFyPTp1s-Zk-SLK0Y0iVjdJUhPl8g',
    appId: '1:711200537692:web:32a4b96701b8381febfa99',
    messagingSenderId: '711200537692',
    projectId: 'spotify-192dif9ab12',
    authDomain: 'spotify-192dif9ab12.firebaseapp.com',
    storageBucket: 'spotify-192dif9ab12.firebasestorage.app',
  );
}
